import { GoogleGenAI, Modality } from "@google/genai";
import type { GenerateContentResponse } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable is not set.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const fileToGenerativePart = (base64: string, mimeType: string) => {
  return {
    inlineData: {
      data: base64,
      mimeType
    },
  };
};

const getMimeType = (dataUrl: string): string => {
    const matches = dataUrl.match(/^data:(.+);base64,/);
    if (matches && matches.length > 1) {
        return matches[1];
    }
    return 'image/jpeg'; // Default fallback
};

export const generateImageWithStyle = async (
  originalImage: string,
  style: string,
  colorPalette?: string | null,
  atmosphere?: string | null,
  imageQuality?: 'standard' | 'high' | null,
): Promise<string> => {
  let prompt = `Analyze the provided image of a room. Your task is to re-decorate this exact room in a ${style} style. It is crucial that you DO NOT alter the core structure of the room. This includes walls, windows, doors, ceiling height, and overall room layout. Only change the furniture, wall colors, flooring, lighting, and decorative items to fit the new style.`;

  if (colorPalette) {
    prompt += ` The desired color palette is ${colorPalette}.`;
  }
  if (atmosphere) {
    prompt += ` The atmosphere should feel ${atmosphere}.`;
  }
  if (imageQuality === 'high') {
    prompt += ` Please render the final image with high fidelity, photorealistic details, and professional-level lighting.`
  }
  
  const mimeType = getMimeType(originalImage);
  const base64Data = originalImage.split(',')[1];
  const imagePart = fileToGenerativePart(base64Data, mimeType);

  const response: GenerateContentResponse = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: { parts: [imagePart, { text: prompt }] },
    config: {
        responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts ?? []) {
    if (part.inlineData) {
      return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No image generated by the API.");
};

export const applyStyleFromReference = async (
  targetImage: string,
  styleReferenceImage: string,
  imageQuality?: 'standard' | 'high' | null,
): Promise<string> => {
    let prompt = `You are an expert interior designer. Your task is to redesign the room in the first image (the target) to perfectly match the aesthetic of the second image (the style reference).
- Replicate the style, color palette, furniture choices, materials, and overall mood from the style reference image.
- CRUCIAL: Do not alter the architectural elements of the target image. The walls, windows, doors, and overall layout of the target room must remain unchanged. You are only re-decorating it.`;

    if (imageQuality === 'high') {
        prompt += ` Please render the final image with high fidelity, photorealistic details, and professional-level lighting.`;
    }

    const targetMimeType = getMimeType(targetImage);
    const targetBase64 = targetImage.split(',')[1];
    const targetImagePart = fileToGenerativePart(targetBase64, targetMimeType);

    const refMimeType = getMimeType(styleReferenceImage);
    const refBase64 = styleReferenceImage.split(',')[1];
    const refImagePart = fileToGenerativePart(refBase64, refMimeType);

    const response: GenerateContentResponse = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: { parts: [targetImagePart, refImagePart, { text: prompt }] },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates?.[0]?.content?.parts ?? []) {
        if (part.inlineData) {
            return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
    }

    throw new Error("No image generated by the API for style application.");
};


export const refineImageWithText = async (
    baseImage: string,
    prompt: string,
    imageQuality?: 'standard' | 'high' | null,
): Promise<string> => {
    const mimeType = getMimeType(baseImage);
    const base64Data = baseImage.split(',')[1];
    const imagePart = fileToGenerativePart(base64Data, mimeType);

    let fullPrompt = prompt;
    if (imageQuality === 'high') {
        fullPrompt += ` (Render the result with high fidelity and photorealistic details.)`;
    }

    const response: GenerateContentResponse = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: { parts: [imagePart, { text: fullPrompt }] },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates?.[0]?.content?.parts ?? []) {
        if (part.inlineData) {
            return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
    }

    throw new Error("No image generated by the API for refinement.");
};


export const getChatResponse = async (prompt: string): Promise<string> => {
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: prompt,
  });
  return response.text;
};

export const getShoppingSuggestions = async (
    baseImage: string,
    prompt: string
): Promise<string> => {
    const mimeType = getMimeType(baseImage);
    const base64Data = baseImage.split(',')[1];
    const imagePart = fileToGenerativePart(base64Data, mimeType);
    const fullPrompt = `Analyze the provided image of a room design. The user is asking: "${prompt}". Based on this, identify relevant furniture or decor items and provide 3-5 fictional, but realistic-looking, shoppable links for similar items. For each item, give it a descriptive name. Format the response as a markdown list. For example:
- **[Minimalist Oak Coffee Table](https://example.com/shop/minimalist-oak-table)** - A beautiful and functional centerpiece for your living room.
- **[Cozy Boucle Accent Chair](https://example.com/shop/boucle-accent-chair)** - Perfect for reading nooks and adding a touch of texture.`;
    
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: { parts: [imagePart, { text: fullPrompt }] },
    });

    return response.text;
};